version: "2"
services:
  product:
    image: product
    ports:
      - "8081:9090"
    networks:
      - spring-miniproject2
    depends_on:
      - mysql-standalone

  mysql-standalone:
    image: mysql:8
    networks:
      - spring-miniproject2
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_DATABASE=product-service-db
networks:
  spring-miniproject2: